setup themes

diff --git a/conf/etc/cont-init.d/02-civicrm b/conf/etc/cont-init.d/02-civicrm
--- a/conf/etc/cont-init.d/02-civicrm
+++ b/conf/etc/cont-init.d/02-civicrm
@@ -1,45 +1,70 @@
 #!/usr/bin/with-contenv sh
+
+fail(){
+  echo "[ Failed ]"
+  echo "1" > /tmp/civicrm
+  return 1
+
+}
+
+success(){
+  echo "[ Success ]"
+  echo "0" > /tmp/civicrm
+  return 0
+
+}
+
+
+
+run(){
+    eval "su - nginx -s /bin/ash -c 'cd /var/www/drupal/ && "$@"'" 
+    return $? 
+}
+
 if [ ! -d /var/www/drupal/web/sites/all/modules/civicrm ] 
 then 
-    wget -q https://download.civicrm.org/civicrm-${CIVICRM_VERSION}-drupal.tar.gz -O /tmp/civicrm.tgz
-    wget -q https://download.civicrm.org/civicrm-${CIVICRM_VERSION}-l10n.tar.gz -O /tmp/civicrm-l10n.tgz
-    wget -q https://raw.githubusercontent.com/civicrm/civicrm-drupal/7.x-master/drush/civicrm.drush.inc -O /root/.drush/civicrm.drush.inc 
-    wget https://github.com/civicrm/org.civicrm.shoreditch/archive/v0.1-alpha31.zip -O /tmp/ext.zip 
-    cd /var/www/drupal
-    vendor/bin/drush cache-clear drush
-
+    echo "> Install "
+    echo ">>> Waiting for database to be ready"
     while ! $( nc -vz ${DATABASE_HOST} ${DATABASE_PORT} ) ;
     do
         sleep 1
     done
    
-    echo "> Installing CiviCRM"
-
-    vendor/bin/drush civicrm-install \
+    echo ">>> Installing CiviCRM"
+    cp /opt/ressources/civicrm.drush.inc /var/www/drupal/drush/civicrm.drush.inc
+    run vendor/bin/drush cc all || fail
+    chmod u+w /var/www/drupal/web/sites/default 
+    run vendor/bin/drush civicrm-install \
         --site_url=${TRUSTED_HOST} \
         --dbhost=${DATABASE_HOST}:${DATABASE_PORT} \
         --dbname=${CIVICRM_DB_NAME} \
         --dbuser=${CIVICRM_DB_USERNAME} \
         --dbpass=${CIVICRM_DB_PASSWORD} \
-        --tarfile=/tmp/civicrm.tgz \
+        --tarfile=/opt/ressources/civicrm.tgz \
         --lang=fr_FR \
-        --langtarfile=/tmp/civicrm-l10n.tgz \
-        --ssl=off
-    unzip /tmp/ext.zip -d /var/www/drupal/web/sites/default/files/civicrm/ext/
-    rm /tmp/* -R || true
-
-    echo "> Installing CiviCRM Extensions"
-    vendor/bin/drush civicrm-ext-install org.civicrm.api4
-    vendor/bin/drush -y pm-enable civicrm_contact_ref civicrmtheme civicrm_engage civicrm_group_roles civicrm_member_roles
+        --langtarfile=/opt/ressources/civicrm-l10n.tgz \
+        --ssl=${CIVICRM_HTTPS} || fail
     
-    chown nginx:nginx /var/www/drupal/web/sites/default/files/civicrm/ext/ -R
-    vendor/bin/drush cache-clear all
-    vendor/bin/drush civicrm-ext-install org.civicrm.shoreditch
+    run unzip -q /opt/ressources/shoreditch.zip -d /var/www/drupal/web/sites/all/modules/civicrm/ext/ || fail
 
-    echo ">>> Setting up Shoreditch"
-    vendor/bin/drush cvapi Setting.create customCSSURL="[civicrm.files]/ext/org.civicrm.shoreditch-0.1-alpha31/css/custom-civicrm.css"
+    echo ">>> Installing Drupal Extensions"
+    run cp /opt/ressources/betterlogin.tar.gz /var/www/drupal/web/sites/all/modules/ 
+    run tar -xzf /var/www/drupal/web/sites/all/modules/betterlogin.tar.gz -C /var/www/drupal/web/sites/all/modules/ 
+    run rm  /var/www/drupal/web/sites/all/modules/betterlogin.tar.gz 
+    run vendor/bin/drush cc all || fail
+    run vendor/bin/drush -y pm-enable civicrm_contact_ref civicrmtheme civicrm_engage civicrm_group_roles civicrm_member_roles betterlogin || fail
+    echo ">>> Installing CiviCRM Extensions"
+    run vendor/bin/drush civicrm-ext-install org.civicrm.shoreditch || fail
+    run vendor/bin/drush cvapi Setting.create customCSSURL="[civicrm.root]/ext/org.civicrm.shoreditch-0.1-alpha31/css/custom-civicrm.css" || fail
+    echo ">>> Setup Drupal Themes"
+    run vendor/bin/drush vset civicrmtheme_theme_admin seven
+    run vendor/bin/drush vset civicrmtheme_theme_public seven
+    run vendor/bin/drush vset admin_theme seven
 
-    chown nginx:nginx web -R
+    run vendor/bin/drush vset site_frontpage civicrm/dashboard
+    run vendor/bin/drush vset site_403 user/login
+
+    
 fi
 
-echo "0" >/tmp/civicrm
+success
